# Common abbrevations of states for each country.
---
Canada:
  AB: "Alberta"
  BC: "British Columbia"
  MB: "Manitoba"
  NB: "New Brunswick"
  NL: "Newfoundland and Labrador"
  NS: "Nova Scotia"
  ON: "Ontario"
  PE: "Prince Edward Island"
  QC: "Quebec"
  SK: "Saskatchewan"
  NT: "Northwest Territories"
  NU: "Nunavut"
  YT: "Yukon"

Mexico:
  AG: "Aguascalientes"
  GC: "Baja California"
  GS: "Baja California Sur"
  CM: "Campeche"
  CS: "Chiapas"
  CH: "Chihuahua"
  CO: "Coahuila"
  CL: "Colima"
  DF: "Distrito Federal"
  DG: "Durango"
  GT: "Guanajuato"
  GR: "Guerrero"
  HG: "Hidalgo"
  JA: "Jalisco"
  EM: "Mexico"
  MI: "Michoacan"
  MO: "Morelos"
  NA: "Nayarit"
  NL: "Nuevo Leon"
  OA: "Oaxaca"
  PU: "Puebla"
  QT: "Queretaro"
  QR: "Quintana Roo"
  SL: "San Luis Potosi"
  SI: "Sinaloa"
  SO: "Sonora"
  TB: "Tabasco"
  TM: "Tamaulipas"
  TL: "Tlaxcala"
  VE: "Veracruz"
  YU: "Yucatan"
  ZA: "Zacatecas"

USA:
  AL: "Alabama"
  AK: "Alaska"
  AS: "American Samoa"
  AZ: "Arizona"
  AR: "Arkansas"
  CA: "California"
  CO: "Colorado"
  CT: "Connecticut"
  DE: "Delaware"
  FM: "Federated States of Micronesia"
  FL: "Florida"
  GA: "Georgia"
  GU: "Guam"
  HA: "Hawaii"
  ID: "Idaho"
  IL: "Illinois"
  IN: "Indiana"
  IO: "Iowa"
  KS: "Kansas"
  KY: "Kentucky"
  LA: "Louisiana"
  ME: "Maine"
  MH: "Marshall Islands"
  MD: "Maryland"
  MA: "Massachusetts"
  MI: "Michigan"
  MN: "Minnesota"
  MS: "Mississippi"
  MO: "Missouri"
  MT: "Montana"
  NE: "Nebraska"
  NV: "Nevada"
  NH: "New Hampshire"
  NJ: "New Jersey"
  NM: "New Mexico"
  NY: "New York"
  NC: "North Carolina"
  ND: "North Dakota"
  NP: "Northern Mariana Islands"
  OH: "Ohio"
  OK: "Oklahoma"
  OR: "Oregon"
  PW: "Palau"
  PA: "Pennsylvania"
  PR: "Puerto Rico"
  RI: "Rhode Island"
  SC: "South Carolina"
  SD: "South Dakota"
  TN: "Tennessee"
  TX: "Texas"
  UT: "Utah"
  VT: "Vermont"
  VI: "Virgin Islands"
  VA: "Virginia"
  WA: "Washington"
  DC: "Washington DC"
  WV: "West Virginia"
  WI: "Wisconsin"
  WY: "Wyoming"

